/* eslint-disable prettier/prettier */
export enum ActionTypes {
  ADD_ALARM_STARTING_TIME = `ADD_ALARM_STARTING_TIME`,
  ADD_ALARM_ENDING_TIME = `ADD_ALARM_ENDING_TIME`,

  TOGGLE_ALARM = `TOGGLE_ALARM`,

  TOGGLE_DAY = `TOGGLE_DAY`,

  SELECT_SOUND = `SELECT_SOUND`,

  TOGGLE_VIBRATION = `TOGGLE_VIBRATION`,

  CHANGE_ALARM_INTERVAL = `CHANGE_ALARM_INTERVAL`
}
